name: 'Deploy Docker to AWS (EC2)'
description: 'Deploy a Docker app to an AWS Virtual Machine (EC2) with Docker Compose'
branding:
  icon: upload-cloud
  color: red
inputs:
  # Checkout
  checkout:
    description: 'Specifies if this action should checkout the code'
    required: false
    default: 'true'
  
  # AWS
  aws_access_key_id:
    description: 'AWS access key ID'
    required: true
  aws_secret_access_key:
    description: 'AWS secret access key'
    required: true
  aws_default_region:
    description: 'AWS default region'
    default: us-east-1
    required: false
  aws_role_to_assume:
    description: 'AWS Role to assume.'
    required: false
  aws_resource_identifier:
    description: 'Set to override the AWS resource identifier for the deployment.  Defaults to `${org}-{repo}-{branch}`.  Use with destroy to destroy specific resources.'
    required: false
  aws_additional_tags:
    description: 'A JSON object of additional tags that will be included on created resources. Example: `{"key1": "value1", "key2": "value2"}`'
    required: false

  # Terraform options
  tf_action: 
    desctiption: 'Option to run Terraform apply / destroy option. Will run plan if nothing defined.'
    required: false
  tf_plan_show_details:
    description: 'Set to true to show a detailed output from Terraform plan.'
    required: false
  tf_state_bucket:
    description: 'AWS S3 bucket to use for Terraform state. Defaults to `${org}-${repo}-{branch}-tf-state`'
    required: false
  tf_state_bucket_destroy:
    description: 'Force purge and deletion of S3 bucket defined if terraform destroy action succeded.'
    required: false

  # SPA Settings
  aws_spa_source_folder:
    description: 'Sources to be stored in the bucket. Coma sepparated list of files possible.'
    required: true
  aws_spa_website_bucket_name:
    description: 'AWS secret access key'
    required: false
  aws_spa_cdn_enabled:
    description: 'AWS session token'
    required: false
  aws_spa_cdn_root_object:
    description: 'AWS default region'
    required: false

  # AWS Route53 Domains abd Certificates
  aws_r53_domain_name:
    description: 'Define the root domain name for the application. e.g. app.com'
    required: false
  aws_r53_sub_domain_name:
    description: 'Define the sub-domain part of the URL. Defaults to `${org}-${repo}-{branch}`'
  aws_r53_root_domain_deploy:
    description: 'Deploy to root domain. Will generate two DNS recrods, one for root, another for www'
    required: false
  aws_r53_enable_cert:
    description: 'Makes the application use a certificate by enabling a certificate lookup.'
    required: false
  aws_r53_cert_arn:
    description: 'Define the certificate ARN to use for the application'
    required: false
  aws_r53_create_root_cert:
    description: 'Generates and manage the root cert for the application'
    required: false
  aws_r53_create_sub_cert: 
    description: 'Generates and manage the sub-domain certificate for the application'
    required: false
    

outputs:
  vm_url:
    description: "The URL of the generated app"
    value: ${{ steps.deploy.outputs.vm_url }}

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      if: ${{ inputs.aws_access_key_id != '' }}
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_default_region }}
        role-to-assume: ${{ inputs.aws_role_to_assume }}

    - name: Deploy with BitOps
      id: deploy
      shell: bash
      env:
        # AWS
        AWS_DEFAULT_REGION: ${{ inputs.aws_default_region }}
        AWS_RESOURCE_IDENTIFIER: ${{ inputs.aws_resource_identifier }}
        AWS_ADDITIONAL_TAGS: ${{ inputs.aws_additional_tags }}
        # TF
        TF_STATE_BUCKET: ${{ inputs.tf_state_bucket }}
        TF_STATE_BUCKET_DESTROY: ${{ inputs.tf_state_bucket_destroy }}
        # SPA
        AWS_SPA_SOURCE_FOLDER: ${{ inputs.aws_spa_source_folder }}
        AWS_SPA_WEBSITE_BUCKET_NAME: ${{ inputs.aws_spa_website_bucket_name }}
        AWS_SPA_CDN_ENABLED: ${{ inputs.aws_spa_cdn_enabled }}
        AWS_SPA_CDN_ROOT_OBJECT: ${{ inputs.aws_spa_cdn_root_object }}
        # AWS Route53 Domains abd Certificates
        AWS_R53_DOMAIN_NAME: ${{ inputs.aws_r53_domain_name }}
        AWS_R53_SUB_DOMAIN_NAME: ${{ inputs.aws_r53_sub_domain_name }}
        AWS_R53_ROOT_DOMAIN_DEPLOY: ${{ inputs.aws_r53_root_domain_deploy }}
        AWS_R53_ENABLE_CERT: ${{ inputs.aws_r53_enable_cert }}
        AWS_R53_CERT_ARN: ${{ inputs.aws_r53_cert_arn }}
        AWS_R53_CREATE_ROOT_CERT: ${{ inputs.aws_r53_create_root_cert }}
        AWS_R53_CREATE_SUB_CERT: ${{ inputs.aws_r53_create_sub_cert }}
      run: |
        echo "running scripts/generate_deploy.sh"
        $GITHUB_ACTION_PATH/scripts/generate_deploy.sh


    - name: Env print
      id: env
      shell: bash
      run: env

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      id: init
      shell: bash
      run: terraform -chdir=$GITHUB_ACTION_PATH/terraform_code init
    
    - name: Terraform Validate
      id: validate
      shell: bash
      run: terraform -chdir=$GITHUB_ACTION_PATH/terraform_code validate
    
    - name: Terraform Plan
      id: plan
      shell: bash
      run: terraform -chdir=$GITHUB_ACTION_PATH/terraform_code plan

    - name: Terraform Show Plan Details
      if: ${{ success () && inputs.tf_show_plan_details == 'true' }}
      shell: bash
      run: |
        echo ${{ steps.plan.outputs.stdout }}
        echo ${{ steps.plan.outputs.stderr }}
        echo ${{ steps.plan.outputs.exitcode }}

    - name: Terraform Apply
      if: ${{ success() && inputs.tf_action == 'apply' }}
      shell: bash
      run: |
        terraform -chdir=$GITHUB_ACTION_PATH/terraform_code apply -auto-approve

    - name: Terraform Destroy
      if: ${{ success() && inputs.tf_action == 'destroy' }}
      shell: bash
      run: |
        terraform -chdir=$GITHUB_ACTION_PATH/terraform_code destroy -auto-approve

    - name: Terraform Destroy
      if: ${{ success() && inputs.tf_action == 'destroy' && inputs.tf_state_bucket_destroy == 'true' }}
      shell: bash
      run: |
        aws s3 rb s3://$TF_STATE_BUCKET --force