# Main Terraform Configuration
#
# This file is intentionally minimal.
# All resources have been organized into separate files for better maintainability:
#
# - s3.tf:          S3 bucket resources and policies
# - cloudfront.tf:  CloudFront distributions
# - route53.tf:     Route53 DNS records
# - certificates.tf: ACM certificates
# - locals.tf:      Local variables and outputs
# - variables.tf:   Input variables
# - provider.tf:    Provider configuration (generated by scripts)
#
# For more information, see the README.md file.
